1    106
0     31
Name: reactiveness, dtype: int64

# Data Exploration and Preprocessing

In [0]:
import numpy as np

In [0]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
import os
os.chdir("/content/drive/My Drive")

In [0]:
import pandas as pd
#alertl = pd.read_csv('drive/My Drive/AlertLevel.csv')
rvbsm = pd.read_csv('RvBsm.csv')
#summary = pd.read_csv('drive/My Drive/Summary.csv')
#eventappid = pd.read_csv('drive/My Drive/EventAppID.csv')
host = pd.read_csv('Host.csv')
#rvzone = pd.read_csv('drive/My Drive/RvZone.csv')
evtwarn = pd.read_csv('EvtWarn.csv')
#vehclass = pd.read_csv('drive/My Drive/RvBasicVehClass.csv')
#spat = pd.read_csv('Spat.csv')

ht_.dropna(thresh=50)

In [0]:
# get unique trip and device. ignore consecutive events with interval less than 2.5s
ignore_interval = 2.5 * 100
e_  = pd.DataFrame(columns=evt_.columns)
i_ = 0
for i, row in evt_.iterrows():
    if i_==0:
        e_.loc[i_] = row
        i_+=1
    else:
        if ((i-1 in evt_.index) and (evt_.loc[i]['Trip']==evt_.loc[i-1]['Trip']) \
        and (evt_.loc[i]['Device']==evt_.loc[i-1]['Device']) and (evt_.loc[i]['Time']-evt_.loc[i-1]['Time']<=ignore_interval)):
            pass
        else:
            e_.loc[i_] = row
            i_+=1
            

NameError: ignored

In [0]:
# e_.loc[0]['Time']-list(host[(host['Device']==e_.loc[0]['Device']) & (host['Trip']==e_.loc[0]['Trip']) & (host['Time']>e_.loc[0]['Time']) & (host['Time']<(e_.loc[0]['Time']+6000)) & (host['BrakeStatus']==1)]['Time'])[0]

In [0]:
# new table with unique warings
e_.head()

In [0]:
# calculate reaction time using host table . max look for 60s
max_look_time = 60 * 100
reactiveness = pd.DataFrame(columns=['Device','Trip','ReactionTime','Time'])
for i,row in e_.iterrows():
    rt = list(host[(host['Device']==row['Device']) & (host['Trip']==row['Trip']) & (host['Time']>row['Time']) & (host['Time']<(row['Time']+max_look_time)) & (host['BrakeStatus']==1)]['Time'])
    if len(rt)>0:
        rt=(rt[0]-row['Time'])/100
    else:
        rt=-1
    reactiveness.loc[i]=[row['Device'],row['Trip'],rt,row['Time']]

In [0]:
reactiveness

In [0]:
evtwarn['EventAppId'].value_counts()

In [0]:
evt_ = evtwarn[(evtwarn['EventAppId'] == 0)]
ignore_interval = 2.5 * 100
e_  = pd.DataFrame(columns=evt_.columns)
i_ = 0
for i, row in evt_.iterrows():
    if i_==0:
        e_.loc[i_] = row
        i_+=1
    else:
        if ((i-1 in evt_.index) and (evt_.loc[i]['Trip']==evt_.loc[i-1]['Trip']) \
        and (evt_.loc[i]['Device']==evt_.loc[i-1]['Device']) and (evt_.loc[i]['Time']-evt_.loc[i-1]['Time']<=ignore_interval)):
            pass
        else:
            e_.loc[i_] = row
            i_+=1
max_look_time = 60 * 100
reactiveness = pd.DataFrame(columns=['Device','Trip','ReactionTime','Time'])
for i,row in e_.iterrows():
    rt = list(host[(host['Device']==row['Device']) & (host['Trip']==row['Trip']) & (host['Time']>row['Time']) & (host['Time']<(row['Time']+max_look_time)) & (host['BrakeStatus']==1)]['Time'])
    if len(rt)>0:
        rt=(rt[0]-row['Time'])/100
    else:
        rt=-1
    reactiveness.loc[i]=[row['Device'],row['Trip'],rt,row['Time']]
reactiveness

In [0]:
evt_ = evtwarn[(evtwarn['EventAppId'] == 1)]
ignore_interval = 2.5 * 100
e_  = pd.DataFrame(columns=evt_.columns)
i_ = 0
for i, row in evt_.iterrows():
    if i_==0:
        e_.loc[i_] = row
        i_+=1
    else:
        if ((i-1 in evt_.index) and (evt_.loc[i]['Trip']==evt_.loc[i-1]['Trip']) \
        and (evt_.loc[i]['Device']==evt_.loc[i-1]['Device']) and (evt_.loc[i]['Time']-evt_.loc[i-1]['Time']<=ignore_interval)):
            pass
        else:
            e_.loc[i_] = row
            i_+=1
max_look_time = 60 * 100
reactiveness = pd.DataFrame(columns=['Device','Trip','ReactionTime','Time'])
for i,row in e_.iterrows():
    rt = list(host[(host['Device']==row['Device']) & (host['Trip']==row['Trip']) & (host['Time']>row['Time']) & (host['Time']<(row['Time']+max_look_time)) & (host['BrakeStatus']==1)]['Time'])
    if len(rt)>0:
        rt=(rt[0]-row['Time'])/100
    else:
        rt=-1
    reactiveness.loc[i]=[row['Device'],row['Trip'],rt,row['Time']]
reactiveness

In [0]:
evt_ = evtwarn[(evtwarn['EventAppId'] == 3)]
ignore_interval = 2.5 * 100
e_  = pd.DataFrame(columns=evt_.columns)
i_ = 0
for i, row in evt_.iterrows():
    if i_==0:
        e_.loc[i_] = row
        i_+=1
    else:
        if ((i-1 in evt_.index) and (evt_.loc[i]['Trip']==evt_.loc[i-1]['Trip']) \
        and (evt_.loc[i]['Device']==evt_.loc[i-1]['Device']) and (evt_.loc[i]['Time']-evt_.loc[i-1]['Time']<=ignore_interval)):
            pass
        else:
            e_.loc[i_] = row
            i_+=1
max_look_time = 60 * 100
reactiveness = pd.DataFrame(columns=['Device','Trip','ReactionTime','Time'])
for i,row in e_.iterrows():
    rt = list(host[(host['Device']==row['Device']) & (host['Trip']==row['Trip']) & (host['Time']>row['Time']) & (host['Time']<(row['Time']+max_look_time)) & (host['BrakeStatus']==1)]['Time'])
    if len(rt)>0:
        rt=(rt[0]-row['Time'])/100
    else:
        rt=-1
    reactiveness.loc[i]=[row['Device'],row['Trip'],rt,row['Time']]
reactiveness

In [0]:
evt_ = evtwarn[(evtwarn['EventAppId'] == 9)]
ignore_interval = 2.5 * 100
e_  = pd.DataFrame(columns=evt_.columns)
i_ = 0
for i, row in evt_.iterrows():
    if i_==0:
        e_.loc[i_] = row
        i_+=1
    else:
        if ((i-1 in evt_.index) and (evt_.loc[i]['Trip']==evt_.loc[i-1]['Trip']) \
        and (evt_.loc[i]['Device']==evt_.loc[i-1]['Device']) and (evt_.loc[i]['Time']-evt_.loc[i-1]['Time']<=ignore_interval)):
            pass
        else:
            e_.loc[i_] = row
            i_+=1
max_look_time = 60 * 100
reactiveness = pd.DataFrame(columns=['Device','Trip','ReactionTime','Time'])
for i,row in e_.iterrows():
    rt = list(host[(host['Device']==row['Device']) & (host['Trip']==row['Trip']) & (host['Time']>row['Time']) & (host['Time']<(row['Time']+max_look_time)) & (host['BrakeStatus']==1)]['Time'])
    if len(rt)>0:
        rt=(rt[0]-row['Time'])/100
    else:
        rt=-1
    reactiveness.loc[i]=[row['Device'],row['Trip'],rt,row['Time']]
reactiveness

In [0]:
evt_ = evtwarn[(evtwarn['EventAppId'] == 10)]
ignore_interval = 2.5 * 100
e_  = pd.DataFrame(columns=evt_.columns)
i_ = 0
for i, row in evt_.iterrows():
    if i_==0:
        e_.loc[i_] = row
        i_+=1
    else:
        if ((i-1 in evt_.index) and (evt_.loc[i]['Trip']==evt_.loc[i-1]['Trip']) \
        and (evt_.loc[i]['Device']==evt_.loc[i-1]['Device']) and (evt_.loc[i]['Time']-evt_.loc[i-1]['Time']<=ignore_interval)):
            pass
        else:
            e_.loc[i_] = row
            i_+=1
max_look_time = 60 * 100
reactiveness = pd.DataFrame(columns=['Device','Trip','ReactionTime','Time'])
for i,row in e_.iterrows():
    rt = list(host[(host['Device']==row['Device']) & (host['Trip']==row['Trip']) & (host['Time']>row['Time']) & (host['Time']<(row['Time']+max_look_time)) & (host['BrakeStatus']==1)]['Time'])
    if len(rt)>0:
        rt=(rt[0]-row['Time'])/100
    else:
        rt=-1
    reactiveness.loc[i]=[row['Device'],row['Trip'],rt,row['Time']]
reactiveness

In [0]:
evt_ = evtwarn[(evtwarn['EventAppId'] == 11)]
ignore_interval = 2.5 * 100
e_  = pd.DataFrame(columns=evt_.columns)
i_ = 0
for i, row in evt_.iterrows():
    if i_==0:
        e_.loc[i_] = row
        i_+=1
    else:
        if ((i-1 in evt_.index) and (evt_.loc[i]['Trip']==evt_.loc[i-1]['Trip']) \
        and (evt_.loc[i]['Device']==evt_.loc[i-1]['Device']) and (evt_.loc[i]['Time']-evt_.loc[i-1]['Time']<=ignore_interval)):
            pass
        else:
            e_.loc[i_] = row
            i_+=1
max_look_time = 60 * 100
reactiveness = pd.DataFrame(columns=['Device','Trip','ReactionTime','Time'])
for i,row in e_.iterrows():
    rt = list(host[(host['Device']==row['Device']) & (host['Trip']==row['Trip']) & (host['Time']>row['Time']) & (host['Time']<(row['Time']+max_look_time)) & (host['BrakeStatus']==1)]['Time'])
    if len(rt)>0:
        rt=(rt[0]-row['Time'])/100
    else:
        rt=-1
    reactiveness.loc[i]=[row['Device'],row['Trip'],rt,row['Time']]
reactiveness

In [0]:
evt_ = evtwarn[(evtwarn['EventAppId'] == 12)]
ignore_interval = 2.5 * 100
e_  = pd.DataFrame(columns=evt_.columns)
i_ = 0
for i, row in evt_.iterrows():
    if i_==0:
        e_.loc[i_] = row
        i_+=1
    else:
        if ((i-1 in evt_.index) and (evt_.loc[i]['Trip']==evt_.loc[i-1]['Trip']) \
        and (evt_.loc[i]['Device']==evt_.loc[i-1]['Device']) and (evt_.loc[i]['Time']-evt_.loc[i-1]['Time']<=ignore_interval)):
            pass
        else:
            e_.loc[i_] = row
            i_+=1
max_look_time = 60 * 100
reactiveness = pd.DataFrame(columns=['Device','Trip','ReactionTime','Time'])
for i,row in e_.iterrows():
    rt = list(host[(host['Device']==row['Device']) & (host['Trip']==row['Trip']) & (host['Time']>row['Time']) & (host['Time']<(row['Time']+max_look_time)) & (host['BrakeStatus']==1)]['Time'])
    if len(rt)>0:
        rt=(rt[0]-row['Time'])/100
    else:
        rt=-1
    reactiveness.loc[i]=[row['Device'],row['Trip'],rt,row['Time']]
reactiveness

# Train an RNN+LSTM Model
Prepare training data and train

In [0]:
import pandas as pd
#alertl = pd.read_csv('AlertLevel.csv')
rvbsm = pd.read_csv('RvBsm.csv')
#summary = pd.read_csv('Summary.csv')
#eventappid = pd.read_csv('EventAppID.csv')
host = pd.read_csv('Host.csv')
#rvzone = pd.read_csv('RvZone.csv')
evtwarn = pd.read_csv('EvtWarn.csv')
#vehclass = pd.read_csv('RvBasicVehClass.csv')
#spat = pd.read_csv('Spat.csv')

In [0]:
evtwarn['Time'] = evtwarn['Time'].astype(str).str.replace(',','').astype('int64')
evtwarn['Device'] = evtwarn['Device'].astype(str).str.replace(',','').astype('int64')
evtwarn['Trip'] = evtwarn['Trip'].astype(str).str.replace(',','').astype('int64')

In [0]:
evt_ = evtwarn[(evtwarn['EventAppId'] == 2)]
ignore_interval = 2.5 * 100
e_  = pd.DataFrame(columns=evt_.columns)
i_ = 0
for i, row in evt_.iterrows():
    if i_==0:
        e_.loc[i_] = row
        i_+=1
    else:
        if ((i-1 in evt_.index) and (evt_.loc[i]['Trip']==evt_.loc[i-1]['Trip']) \
        and (evt_.loc[i]['Device']==evt_.loc[i-1]['Device']) and (evt_.loc[i]['Time']-evt_.loc[i-1]['Time']<=ignore_interval)):
            pass
        else:
            e_.loc[i_] = row
            i_+=1
max_look_time = 60 * 100
reactiveness = pd.DataFrame(columns=['Device','Trip','ReactionTime','Time'])
for i,row in e_.iterrows():
    rt = list(host[(host['Device']==row['Device']) & (host['Trip']==row['Trip']) & (host['Time']>row['Time']) & (host['Time']<(row['Time']+max_look_time)) & (host['BrakeStatus']==1)]['Time'])
    if len(rt)>0:
        rt=(rt[0]-row['Time'])/100
    else:
        rt=-1
    reactiveness.loc[i]=[row['Device'],row['Trip'],rt,row['Time']]
reactiveness.head()

Device   Trip  ReactionTime      Time
0  2004.0   54.0           6.0  109450.0
1  2004.0   55.0          10.0    9800.0
2  2008.0   61.0           0.5  222650.0
3  2147.0  156.0           0.5  136900.0
4  2331.0   20.0           0.5  194450.0

In [0]:
# label reactiveness : less that 1sec as 1
reactiveness['reactiveness'] = reactiveness['ReactionTime'].map(lambda x: 1 if abs(x)<1 else 0)

In [0]:
# Features: ['BrakeStatus','Speed','ThrottlePosPct', 'StreerAngle']
# get features from host table into x_train, calculate max len of the 
x_train = []
y_train = []
max_len = -float('inf')

for i,row in reactiveness.iterrows():
    x=(host[(host['Device']==row['Device']) & (host['Trip']==row['Trip'])][['BrakeStatus','Speed','ThrottlePosPct','SteerAngle', 'LongAccel']]).values
    if len(x)>=max_len:
        max_len = len(x)
    x_train.append(x)
    y_train.append(row['reactiveness'])

In [0]:
# create same length by appending zeros
import numpy as np
x_t = []
for x in x_train:
    zeros = np.zeros((max_len-len(x),5))
    x_t.append(np.append(x,zeros,axis=0))

In [0]:
#create train, val sets
from sklearn.model_selection import train_test_split
x_train_res, x_val_res, y_train_res, y_val_res = train_test_split(np.array(x_t), np.array(y_train),
                                                  test_size = .1,
                                                  random_state=12)

In [0]:
#imbalance data handling, only for x_train
from imblearn.over_sampling import SMOTENC
smote_nc = SMOTENC(categorical_features=[0], random_state=0)
flat_x = x_train_res.reshape([x_train_res.shape[0],51700])
    #temp_x, temp_y = sm.fit_sample(flat_trip, np.array([reactiveness]))
temp_x, temp_y = smote_nc.fit_sample(flat_x, y_train_res)

In [0]:
x_trai

(160, 5)

In [0]:
#unflatten data:
x_ = temp_x.reshape([temp_x.shape[0],10340,5])
#set y = the y with more data points
y_ = temp_y
from sklearn.utils import shuffle
x_, y_ = shuffle(x_, y_, random_state=0)

In [0]:
def normalize(x, num_features):
  #where x is a col
  #axis = 
  maxval = x.max(axis = (0,1))
  minval = x.min(axis = (0,1))
  for i in np.arange(num_features):
    x[:,:,i:i+1] = (x[:,:,i:i+1]-minval[i])/(maxval[i]-minval[i])
  return x

In [0]:
a = np.array([[[1.0,2.0],
              [3.0,4.0]],
             [[5.0,6.0],
              [7.0,8.0]]])
#normalize
import numpy as np

In [0]:
#try normalizing array of only 1's...
b = np.array([[[1.0,2.0],
              [0.0,4.0]],
             [[0.0,6.0],
              [1.0,1.0]]])
normalize(b,2)

array([[[1. , 0.2],
        [0. , 0.6]],

       [[0. , 1. ],
        [1. , 0. ]]])

In [0]:
#https://stackoverflow.com/questions/42460217/how-to-normalize-a-4d-numpy-array
#how to noramlize on a 3d dataset

array([[[0., 0.],
        [0., 0.]],

       [[1., 1.],
        [1., 1.]]])

In [0]:
c = x_[:,:,:1]
c[c <.5].shape
c[c>.5].shape

(180367,)

In [0]:
#normalize
normalize(x_,5)


array([[[0.        , 0.27678134, 0.        , 0.50724882, 0.68533332],
        [0.        , 0.27678134, 0.        , 0.49483433, 0.67466665],
        [0.        , 0.27183993, 0.        , 0.49159699, 0.67466665],
        ...,
        [0.        , 0.        , 0.        , 0.49815612, 0.68041236],
        [0.        , 0.        , 0.        , 0.49815612, 0.68041236],
        [0.        , 0.        , 0.        , 0.49815612, 0.68041236]],

       [[0.        , 0.31179107, 0.10548281, 0.51250025, 0.70621892],
        [0.        , 0.31261635, 0.06592676, 0.50239077, 0.70029898],
        [0.        , 0.30876086, 0.0263707 , 0.49544537, 0.68226142],
        ...,
        [0.        , 0.        , 0.        , 0.49815612, 0.68041236],
        [0.        , 0.        , 0.        , 0.49815612, 0.68041236],
        [0.        , 0.        , 0.        , 0.49815612, 0.68041236]],

       [[0.        , 0.35187899, 0.03703704, 0.49556625, 0.66133332],
        [0.        , 0.3477306 , 0.01851852, 0.49581961, 0.6

In [0]:
x_[:,:,:1][x_[:,:,:1]>.5] = 1
x_[:,:,:1][x_[:,:,:1]<=.5] = 0

In [0]:
!pip install keras_metrics

In [0]:
# imports
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, LSTM, CuDNNLSTM 
from sklearn.model_selection import train_test_split
import keras_metrics

Using TensorFlow backend.


In [0]:
x_.shape

(176, 51700)

In [0]:
# binary classification lstm model
model = Sequential()
model.add(LSTM(32,input_shape=(x_.shape[1:]),activation='relu',return_sequences=True))
model.add(Dropout(0.2))

model.add(LSTM(32,activation='relu'))
#model.add(Dropout(0.2))

model.add(Dense(32,activation='relu'))
model.add(Dropout(0.2))

model.add(Dense(1, activation='sigmoid'))

In [0]:
# complie
model.compile(loss='binary_crossentropy', optimizer=tf.keras.optimizers.Adam(lr=0.0001)
,metrics=['accuracy'])

In [0]:
x_.shape

(194, 10340, 5)

In [0]:
# fit
#x_train, x_test, y_train, y_test = train_test_split(x_, y_, test_size=0.2, random_state=42)
model.fit(x_,y_,epochs=2)

Epoch 1/2
194/194 [==============================] - 97s 498ms/sample - loss: 0.6939 - acc: 0.5000
Epoch 2/2
194/194 [==============================] - 95s 488ms/sample - loss: 0.6928 - acc: 0.5000


In [0]:
model.predict_classes(x_)

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
    

In [0]:
y_true

array([0., 0., 0., 1., 1., 1., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 1., 1.,
       1., 0., 1., 0., 1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 0., 0., 1.,
       1., 0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1.,
       1., 0., 0., 0., 1., 0., 1., 1., 0., 0., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 1., 0.,
       1., 1., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0., 0., 1., 0., 1., 1.,
       1., 1., 0., 1., 1., 1., 0., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0.,
       1., 1., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 1., 1., 1., 1.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 1.,
       1., 1., 1., 1., 1., 0., 0.])

In [0]:
from sklearn.metrics import confusion_matrix
y_true = y_
y_pred = model.predict(x_)
ConfusionMatrix=pd.DataFrame(confusion_matrix(y_true, y_pred), \
                             columns=['Predicted low','Predicted medium','Predicted high'], \
                             index=['Actual low','Actual medium','Actual high'])
print ('Confusion matrix of test data is: \n',ConfusionMatrix)

ValueError: ignored

In [0]:
from sklearn.metrics import precision_score
print('Average precision for 3 classes is: \n', precision_score(y_true,y_pred,average = None))
from sklearn.metrics import recall_score
print('Average recall for 3 classes is : \n', recall_score(y_true,y_pred,average = None))

# Train on smaller subset of trips



In [0]:
import pandas as pd
import numpy as np

In [0]:
alertl = pd.read_csv('AlertLevel.csv')
rvbsm = pd.read_csv('RvBsm.csv')
summary = pd.read_csv('Summary.csv')
eventappid = pd.read_csv('EventAppID.csv')
host = pd.read_csv('Host.csv')
rvzone = pd.read_csv('RvZone.csv')
evtwarn = pd.read_csv('EvtWarn.csv')
vehclass = pd.read_csv('RvBasicVehClass.csv')
spat = pd.read_csv('Spat.csv')

In [0]:
evt_ = evtwarn[(evtwarn['EventAppId'] == 2)]
ignore_interval = 2.5 * 100
e_  = pd.DataFrame(columns=evt_.columns)
i_ = 0
for i, row in evt_.iterrows():
    if i_==0:
        e_.loc[i_] = row
        i_+=1
    else:
        if ((i-1 in evt_.index) and (evt_.loc[i]['Trip']==evt_.loc[i-1]['Trip']) \
        and (evt_.loc[i]['Device']==evt_.loc[i-1]['Device']) and (evt_.loc[i]['Time']-evt_.loc[i-1]['Time']<=ignore_interval)):
            pass
        else:
            e_.loc[i_] = row
            i_+=1
max_look_time = 60 * 100
reactiveness = pd.DataFrame(columns=['Device','Trip','ReactionTime','Time'])
for i,row in e_.iterrows():
    rt = list(host[(host['Device']==row['Device']) & (host['Trip']==row['Trip']) & (host['Time']>row['Time']) & (host['Time']<(row['Time']+max_look_time)) & (host['BrakeStatus']==1)]['Time'])
    if len(rt)>0:
        rt=(rt[0]-row['Time'])/100
    else:
        rt=-1
    reactiveness.loc[i]=[row['Device'],row['Trip'],rt,row['Time']]
reactiveness.head()

In [0]:
# label reactiveness : less that 1sec as 1
reactiveness['reactiveness'] = reactiveness['ReactionTime'].map(lambda x: 1 if abs(x)<1 else 0)

In [0]:
# drop duplicates (for now) (later average?)
reactiveness = reactiveness.drop_duplicates(['Device','Trip'])

In [0]:
reactiveness['reactiveness'].value_counts()

In [0]:
# Features: ['BrakeStatus','Speed','ThrottlePosPct', 'StreerAngle']
# get features from host table into x_train, divided into smaller chunks
x_train = []
y_train = []
chunk_size = 100

for i,row in reactiveness.iterrows():
    x=(host[(host['Device']==row['Device']) & (host['Trip']==row['Trip'])][['BrakeStatus','Speed','ThrottlePosPct','SteerAngle']]).values
    for j in range(0,len(x)-chunk_size,chunk_size):
        x_train.append(x[j:j+chunk_size])
        y_train.append(row['reactiveness'])

In [0]:
# convert to np arrays
x_ = np.array(x_train)
y_ = np.array(y_train)
from sklearn.utils import shuffle
x_, y_ = shuffle(x_, y_, random_state=0)

In [0]:
# imports
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, LSTM, CuDNNLSTM 
from sklearn.model_selection import train_test_split

In [0]:
# binary classification lstm model
model = Sequential()
model.add(LSTM(128,input_shape=(x_.shape[1:]),activation='relu',return_sequences=True))
model.add(Dropout(0.2))

model.add(LSTM(128,activation='relu'))
model.add(Dropout(0.2))

model.add(Dense(32,activation='relu'))
model.add(Dropout(0.2))

model.add(Dense(1, activation='sigmoid'))

In [0]:
# complie
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [0]:
# fit
x_train, x_test, y_train, y_test = train_test_split(x_, y_, test_size=0.2, random_state=42)
model.fit(x_train,y_train,epochs=1,validation_data=(x_test,y_test))